{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aspects",
    "version": "6.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.22.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aspects-6.2.7.jar",
          "url": "spring-aspects-6.2.7.jar",
          "size": 49860,
          "sha512": "59868314e3a4861751a0692b716a56b1890d8144a4cc460ea7eeff91f3a7e5928710710be49ca39476b993a9cc622c17d8c3ddf5d375a9060ba481f521476ddb",
          "sha256": "e2f764b6a9e3244c313216cd92af07165b00f32a666f2480c8f33ed6c7aff9f6",
          "sha1": "52461ec85ce1dc6e80fdca92c85bab9faebc0509",
          "md5": "0649eafc42f62ab42e4ab5da61504cf0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.22.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aspects-6.2.7.jar",
          "url": "spring-aspects-6.2.7.jar",
          "size": 49860,
          "sha512": "59868314e3a4861751a0692b716a56b1890d8144a4cc460ea7eeff91f3a7e5928710710be49ca39476b993a9cc622c17d8c3ddf5d375a9060ba481f521476ddb",
          "sha256": "e2f764b6a9e3244c313216cd92af07165b00f32a666f2480c8f33ed6c7aff9f6",
          "sha1": "52461ec85ce1dc6e80fdca92c85bab9faebc0509",
          "md5": "0649eafc42f62ab42e4ab5da61504cf0"
        }
      ]
    }
  ]
}
