{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.6.15.Final"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.5.0.jar",
          "url": "spring-boot-starter-data-jpa-3.5.0.jar",
          "size": 4761,
          "sha512": "1de1c81048255a36c91d63963554fb333d5a7c77191f91c145c7709f206216af0ab06988217e1130fcad357c73c400705312f678dea0b094ef40a6e0226917e2",
          "sha256": "c8d1b040ae3d85084c6db38b5b0fa785645bac0ff3404ce5c8fc623c34e2a514",
          "sha1": "1f1b632678d5516b5866a82b282541b18f6bf84c",
          "md5": "3d6c9f91b2c4e790a76c768b54dd5e58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.6.15.Final"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.5.0.jar",
          "url": "spring-boot-starter-data-jpa-3.5.0.jar",
          "size": 4761,
          "sha512": "1de1c81048255a36c91d63963554fb333d5a7c77191f91c145c7709f206216af0ab06988217e1130fcad357c73c400705312f678dea0b094ef40a6e0226917e2",
          "sha256": "c8d1b040ae3d85084c6db38b5b0fa785645bac0ff3404ce5c8fc623c34e2a514",
          "sha1": "1f1b632678d5516b5866a82b282541b18f6bf84c",
          "md5": "3d6c9f91b2c4e790a76c768b54dd5e58"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.5.0-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-3.5.0-javadoc.jar",
          "size": 4761,
          "sha512": "1de1c81048255a36c91d63963554fb333d5a7c77191f91c145c7709f206216af0ab06988217e1130fcad357c73c400705312f678dea0b094ef40a6e0226917e2",
          "sha256": "c8d1b040ae3d85084c6db38b5b0fa785645bac0ff3404ce5c8fc623c34e2a514",
          "sha1": "1f1b632678d5516b5866a82b282541b18f6bf84c",
          "md5": "3d6c9f91b2c4e790a76c768b54dd5e58"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.5.0-sources.jar",
          "url": "spring-boot-starter-data-jpa-3.5.0-sources.jar",
          "size": 4761,
          "sha512": "1de1c81048255a36c91d63963554fb333d5a7c77191f91c145c7709f206216af0ab06988217e1130fcad357c73c400705312f678dea0b094ef40a6e0226917e2",
          "sha256": "c8d1b040ae3d85084c6db38b5b0fa785645bac0ff3404ce5c8fc623c34e2a514",
          "sha1": "1f1b632678d5516b5866a82b282541b18f6bf84c",
          "md5": "3d6c9f91b2c4e790a76c768b54dd5e58"
        }
      ]
    }
  ]
}
