name: 평일 폴더 만들기

on:
  schedule:
    - cron: '0 23 * * *' # UTC 기준 23시는 한국 시간(KST) 08시
  workflow_dispatch:

jobs:
  create-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up current date
        run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: 폴더 생성 및 파일 생성
        run: |
          mkdir -p $TODAY/기본
          mkdir -p $TODAY/심화
          touch $TODAY/기본/01.js
          touch $TODAY/심화/01.js

      - name: commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add $TODAY
          git commit -m "폴더 생성 : $TODAY"
          git push
