name: 평일 폴더 만들기

on:
  schedule:
    - cron: '0 23 * * *' # UTC 기준 23시는 한국 시간(KST) 08시
  workflow_dispatch:

jobs:
  create-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up current date
        run: echo "TODAY=$(date -d '+1 day' +'%Y%m%d')" >> $GITHUB_ENV

      - name: 폴더 생성 및 파일 생성
        run: |
          mkdir -p 02_vue/$TODAY/기본
          mkdir -p 02_vue/$TODAY/심화
          touch 02_vue/$TODAY/기본/01.js
          touch 02_vue/$TODAY/심화/01.js

      - name: commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "guddnboy"
          git config --global user.email "hung3018@naver.com"
          git add $TODAY
          git commit -m "폴더 생성 : $TODAY" || exit 0  # 변경 사항 없으면 에러 방지
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
