name: 평일 폴더 만들기

on:
  schedule:
    - cron: '0 23 * * *' # UTC 기준 23시는 한국 시간(KST) 08시
  workflow_dispatch:

jobs:
  create-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up current date
        run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create directories
        run: |
          mkdir -p $TODAY/기본
          mkdir -p $TODAY/심화
